### ISSUE TITLE
Some plugin's links are not working

### ISSUE THREAD

**Issue by Elardzhi** [ionic-team/capacitor-plugin-registry#37]
For example, this plugin is listed, but the link is not working:
[@modea/capacitor-salesforce-chat](https://bitbucket.org/modea/modea-capacitor-salesforce-chat/src.git)

**Comment by dtarnawsky** [comment]
Yes, this is just a reflection of what is in npm:
[https://www.npmjs.com/package/@modea/capacitor-salesforce-chat](https://www.npmjs.com/package/@modea/capacitor-salesforce-chat)

The repository listing is to a **private** repo that isnt working for you because you/we do not have access to it.

**Comment by Elardzhi** [comment]
Thank you!
